name: "GPIO Info Logger"
version: "1.0.2"
slug: "gpio_info_logger"
description: "Logt GPIO info met gpioinfo binary"
arch:
  - aarch64
startup: application
init: false
hassio_api: false
hassio_role: default
homeassistant_api: false
privileged:
  - SYS_RAWIO
devices:
  - /dev/gpiochip0
  - /dev/gpiochip1
